In [53]:
import pandas as pd

df= pd.read_csv('../data/raw/superstore.csv')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2.0,0.00,41.9136
1,2,CA-2017-152156,11/8/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3.0,0.00,219.5820
2,3,CA-2017-138688,6/12/2017,6/16/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2.0,0.00,6.8714
3,4,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5.0,0.45,-383.0310
4,5,US-2016-108966,10/11/2016,10/18/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2.0,0.20,2.5164

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10800 entries, 0 to 10799
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         10800 non-null  object
 1   Order ID       10800 non-null  object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9983 non-null   float64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   float64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(5), object(16)
memory usage: 1.7+ MB

In [55]:
df.shape

(10800, 21)

In [56]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [57]:
df.isna().sum()

Row ID             0
Order ID           0
Order Date       806
Ship Date        806
Ship Mode        806
Customer ID      806
Customer Name    806
Segment          806
Country          806
City             806
State            806
Postal Code      817
Region           806
Product ID       806
Category         806
Sub-Category     806
Product Name     806
Sales            806
Quantity         806
Discount         806
Profit           806
dtype: int64

In [58]:
df.duplicated().sum()

np.int64(504)

In [59]:
df[df.duplicated()].head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
10001,Yes,CA-2015-100762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10002,Yes,CA-2015-100762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10003,Yes,CA-2015-100762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10006,Yes,CA-2015-102652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007,Yes,CA-2015-102652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [60]:
df.iloc[9988:10010]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9988,9989,CA-2018-163629,11/17/2018,11/21/2018,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605.0,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5.0,0.0,55.6470
9989,9990,CA-2015-110422,1/21/2015,1/23/2015,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3.0,0.2,4.1028
9990,9991,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2.0,0.0,15.6332
9991,9992,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2.0,0.2,19.3932
9992,9993,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4.0,0.0,13.3200
9993,9994,CA-2018-119914,5/4/2018,5/9/2018,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2.0,0.0,72.9480
9994,Person,Region,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9995,Anna Andreadi,West,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,Chuck Magee,East,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,Kelly Williams,Central,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,Cassandra Brandow,South,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,Returned,Order ID,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10000,Yes,CA-2015-100762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10001,Yes,CA-2015-100762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10002,Yes,CA-2015-100762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10003,Yes,CA-2015-100762,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10004,Yes,CA-2015-100867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10005,Yes,CA-2015-102652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10006,Yes,CA-2015-102652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10007,Yes,CA-2015-102652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10008,Yes,CA-2015-102652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10009,Yes,CA-2015-103373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [61]:
orders = df.iloc[:9994]
orders.shape

(9994, 21)

In [62]:
orders.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2015-110422,1/21/2015,1/23/2015,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180.0,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3.0,0.2,4.1028
9990,9991,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2.0,0.0,15.6332
9991,9992,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2.0,0.2,19.3932
9992,9993,CA-2018-121258,2/26/2018,3/3/2018,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627.0,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4.0,0.0,13.3200
9993,9994,CA-2018-119914,5/4/2018,5/9/2018,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683.0,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2.0,0.0,72.9480

In [63]:
people = df.iloc[9995:9999, :2]
print(people)

                 Row ID Order ID
9995      Anna Andreadi     West
9996        Chuck Magee     East
9997     Kelly Williams  Central
9998  Cassandra Brandow    South

In [64]:
people.columns = ['person', 'region']
print(people)

                 person   region
9995      Anna Andreadi     West
9996        Chuck Magee     East
9997     Kelly Williams  Central
9998  Cassandra Brandow    South

In [65]:
people = people.reset_index(drop=True)
print(people)

              person   region
0      Anna Andreadi     West
1        Chuck Magee     East
2     Kelly Williams  Central
3  Cassandra Brandow    South

In [66]:
returns = df.iloc[10000:,:2]
print(returns.head(10))

      Row ID        Order ID
10000    Yes  CA-2015-100762
10001    Yes  CA-2015-100762
10002    Yes  CA-2015-100762
10003    Yes  CA-2015-100762
10004    Yes  CA-2015-100867
10005    Yes  CA-2015-102652
10006    Yes  CA-2015-102652
10007    Yes  CA-2015-102652
10008    Yes  CA-2015-102652
10009    Yes  CA-2015-103373

In [67]:
returns= returns.reset_index(drop=True)
returns.columns = ['returned','order_id']
print(returns.head(15))

   returned        order_id
0       Yes  CA-2015-100762
1       Yes  CA-2015-100762
2       Yes  CA-2015-100762
3       Yes  CA-2015-100762
4       Yes  CA-2015-100867
5       Yes  CA-2015-102652
6       Yes  CA-2015-102652
7       Yes  CA-2015-102652
8       Yes  CA-2015-102652
9       Yes  CA-2015-103373
10      Yes  CA-2015-103744
11      Yes  CA-2015-103744
12      Yes  CA-2015-103940
13      Yes  CA-2015-103940
14      Yes  CA-2015-103940

In [68]:
new_columns = []
for column in orders.columns:
    column= column.lower()
    column= column.replace(' ','_')
    column= column.replace('-','_')
    new_columns.append(column)
print(new_columns)

['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode', 'customer_id', 'customer_name', 'segment', 'country', 'city', 'state', 'postal_code', 'region', 'product_id', 'category', 'sub_category', 'product_name', 'sales', 'quantity', 'discount', 'profit']

In [69]:
orders.columns = new_columns
orders.columns

Index(['row_id', 'order_id', 'order_date', 'ship_date', 'ship_mode',
       'customer_id', 'customer_name', 'segment', 'country', 'city', 'state',
       'postal_code', 'region', 'product_id', 'category', 'sub_category',
       'product_name', 'sales', 'quantity', 'discount', 'profit'],
      dtype='object')

In [70]:
west_orders= orders[orders['region'] == 'West']
print(west_orders.head(10))

   row_id        order_id order_date   ship_date       ship_mode customer_id  \
2       3  CA-2017-138688  6/12/2017   6/16/2017    Second Class    DV-13045
5       6  CA-2015-115812   6/9/2015   6/14/2015  Standard Class    BH-11710
6       7  CA-2015-115812   6/9/2015   6/14/2015  Standard Class    BH-11710
7       8  CA-2015-115812   6/9/2015   6/14/2015  Standard Class    BH-11710
8       9  CA-2015-115812   6/9/2015   6/14/2015  Standard Class    BH-11710
9      10  CA-2015-115812   6/9/2015   6/14/2015  Standard Class    BH-11710
10     11  CA-2015-115812   6/9/2015   6/14/2015  Standard Class    BH-11710
11     12  CA-2015-115812   6/9/2015   6/14/2015  Standard Class    BH-11710
13     14  CA-2017-161389  12/5/2017  12/10/2017  Standard Class    IM-15070
17     18  CA-2015-167164  5/13/2015   5/15/2015    Second Class    AG-10270

      customer_name    segment        country         city  ... postal_code  \
2   Darrin Van Huff  Corporate  United States  Los Angeles  ...     90036.0
5   Brosina Hoffman   Consumer  United States  Los Angeles  ...     90032.0
6   Brosina Hoffman   Consumer  United States  Los Angeles  ...     90032.0
7   Brosina Hoffman   Consumer  United States  Los Angeles  ...     90032.0
8   Brosina Hoffman   Consumer  United States  Los Angeles  ...     90032.0
9   Brosina Hoffman   Consumer  United States  Los Angeles  ...     90032.0
10  Brosina Hoffman   Consumer  United States  Los Angeles  ...     90032.0
11  Brosina Hoffman   Consumer  United States  Los Angeles  ...     90032.0
13     Irene Maddox   Consumer  United States      Seattle  ...     98103.0
17  Alejandro Grove   Consumer  United States  West Jordan  ...     84084.0

    region       product_id         category sub_category  \
2     West  OFF-LA-10000240  Office Supplies       Labels
5     West  FUR-FU-10001487        Furniture  Furnishings
6     West  OFF-AR-10002833  Office Supplies          Art
7     West  TEC-PH-10002275       Technology       Phones
8     West  OFF-BI-10003910  Office Supplies      Binders
9     West  OFF-AP-10002892  Office Supplies   Appliances
10    West  FUR-TA-10001539        Furniture       Tables
11    West  TEC-PH-10002033       Technology       Phones
13    West  OFF-BI-10003656  Office Supplies      Binders
17    West  OFF-ST-10000107  Office Supplies      Storage

                                         product_name     sales  quantity  \
2   Self-Adhesive Address Labels for Typewriters b...    14.620       2.0
5   Eldon Expressions Wood and Plastic Desk Access...    48.860       7.0
6                                          Newell 322     7.280       4.0
7                      Mitel 5320 IP Phone VoIP phone   907.152       6.0
8   DXL Angle-View Binders with Locking Rings by S...    18.504       3.0
9                    Belkin F5C206VTEL 6 Outlet Surge   114.900       5.0
10           Chromcraft Rectangular Conference Tables  1706.184       9.0
11      Konftel 250 Conference phone - Charcoal black   911.424       4.0
13        Fellowes PB200 Plastic Comb Binding Machine   407.976       3.0
17                         Fellowes Super Stor/Drawer    55.500       2.0

    discount    profit
2        0.0    6.8714
5        0.0   14.1694
6        0.0    1.9656
7        0.2   90.7152
8        0.2    5.7825
9        0.0   34.4700
10       0.2   85.3092
11       0.2   68.3568
13       0.2  132.5922
17       0.0    9.9900

[10 rows x 21 columns]

In [71]:
orders['region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [72]:
orders.groupby('region')['order_id'].count()

region
Central    2323
East       2848
South      1620
West       3203
Name: order_id, dtype: int64

In [73]:
orders.groupby('region').size()

region
Central    2323
East       2848
South      1620
West       3203
dtype: int64

In [74]:
orders.groupby('region')['order_id'].nunique()

region
Central    1175
East       1401
South       822
West       1611
Name: order_id, dtype: int64

In [75]:
orders.groupby('region')['sales'].sum()

region
Central    501239.8908
East       678781.2400
South      391721.9050
West       725457.8245
Name: sales, dtype: float64

In [76]:
orders.to_csv('../data/processed/orders.csv', index= False)
people.to_csv('../data/processed/people.csv', index= False)
returns.to_csv('../data/processed/returns.csv', index= False)